/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mingyuju' at '17. 7. 11 오후 10:19' with Gradle 2.14.1
 *
 * @author mingyuju, @date 17. 7. 11 오후 10:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
